### ISSUE TITLE
Right clicking anywhere seems to crash

### ISSUE THREAD

**Issue by JustBeefalo** [azuntik/Amidst-Seed-Hunter#2]
Using v.0.2.3

Error: line 22191 in Amidst.Seed.Hunter.v0.2.3 Unknown function name.

Activated whenever you right click on anything that does not open a menu. First discovered when trying to remove a preset. The same error occurs when selecting "remove this preset," which guides me to believe the two issues are related.

**Comment by azuntik** [comment]
Unfortunately, that feature wasn't fully implemented when the last build was created and it probably won't ever be implemented in this project. I've started a complete re-write in Python that aims to be cross-platform, so I've more or less abandoned this project.

In the meantime, you can still remove presets by clicking the "Remove preset..." button on the options tab. It will open a window showing the presets that exist. You can then select the preset(s) you don't want any more and click OK and they'll be removed.

As for the right-click thing, if it doesn't take long, I'll remove it entirely. It wasn't fully implemented and it always felt cludgy anyway. Until then, your work-around is to just not right-click anything. :)
